### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by volodymyrkepsha** [YueLiao/PPDM#13]
Hello, I built PPDM as it is written in Installation.
But when I launch the training I got this:
What might be the problem ?

![Screenshot from 2020-06-22 14-46-34](https://user-images.githubusercontent.com/54175926/85291955-8145fe80-b49b-11ea-962b-33cb92d30e8d.png)

I'm using AWS g4dn.xlarge machine.

**Comment by YueLiao** [comment]
It may be caused by the wrong cuda version. I guess that you use cuda 10，but the dcn only supports cuda 9. I plan to rewrite the repo by cuda 10 and pytorch1.4 recently.

**Comment by volodymyrkepsha** [comment]
@YueLiao thanks for quick response ! 
Yep, I know about CUDA version, for that reason I've changed the symlink of the CUDA from 10 to 9.
like this:
```
sudo rm -fr  /usr/local/cuda
ln -s /usr/local/cuda-9 /usr/local/cuda
```

**Comment by YueLiao** [comment]
The error is caused by the mismatching cuda version when compiling DCN and running the code. You need to modify the PATH likes:
export PATH="$CUDA_HOME/bin:${PATH}"
export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
export LD_LIBRARY_PATH="$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDA_HOME/include $CFLAGS"

**Comment by volodymyrkepsha** [comment]
Sorry for a long reply.
Unfortunately, it didn't work. 
Looking forward for the solution for CUDA 10.
Thanks !

**Comment by Alasile** [comment]
> 抱歉，回复很长。 不幸的是，它没有用。 期待 CUDA 10 的解决方案。 谢谢
Did you solve it? I encountered the same problem, I also checked the version and still reported this error

**Comment by YueLiao** [comment]
> > 抱歉，回复很长。 不幸的是，它没有用。 期待 CUDA 10 的解决方案。 谢谢
> > Did you solve it? I encountered the same problem, I also checked the version and still reported this error

pt1 branch has already supported cuda10~
