### ISSUE TITLE
Question about the result on the HOI-A dataset

### ISSUE THREAD

**Issue by GWwangshuo** [YueLiao/PPDM#24]
Could you please releaze the pretrained model on the HOI-A dataset? Thanks a lot.

**Comment by YueLiao** [comment]
About the HOI-A dataset, including pretraining model, can be seen in #8 .

**Comment by GWwangshuo** [comment]
> About the HOI-A dataset, including pretraining model, can be seen in #8 .

Thanks for your suggestion. I still have some questions. Could you also please provide the specific HOI-A class dict and HOI-A verb dict? e.g., hoia_class_dict = {1: 'person', ...}; hoia_ver_dict = {1: 'smoking'}

**Comment by YueLiao** [comment]
> > About the HOI-A dataset, including pretraining model, can be seen in #8 .
> 
> Thanks for your suggestion. I still have some questions. Could you also please provide the specific HOI-A class dict and HOI-A verb dict? e.g., hoia_class_dict = {1: 'person', ...}; hoia_ver_dict = {1: 'smoking'}

More about HOI-W/HOI-A dataset can be seen in this [page](http://picdataset.com/challenge/dataset/HOI-W/) and this [repo](https://github.com/YueLiao/PIC_HOIW).

**Comment by llrebecca** [comment]
Hi, I checked #8 and the above repo, but I only see the model for HOI-W. I still cannot find the HOI-A dataset, and the trained model for HOI-A. Where can I find HOI-A dataset? Thank you!

**Comment by YueLiao** [comment]
> Hi, I checked #8 and the above repo, but I only see the model for HOI-W. I still cannot find the HOI-A dataset, and the trained model for HOI-A. Where can I find HOI-A dataset? Thank you!

The HOI-A and HOI-W are accurately the same dataset, and all "HOI-A" results reported in CVPR paper are conducted on HOI-W for a fair comparison with the methods from the PIC 2.0 challenge.  Because the HOI-W is in public before CVPR deadlines, to avoid breaking the double-blind rules, we renaming the "HOI-W" as "HOI-A" (the comparing results from the PIC leaderboard also removed in the submitted version).  The HOI-A is a refined version, which will be released with the PIC 3.0 challenge.

**Comment by llrebecca** [comment]
I see. Thank you!

**Comment by llrebecca** [comment]
Hi, may I ask for the training script or hyperparameters for HOI-A dataset? Thanks!
