### ISSUE TITLE
Could you please provide model perfomance on HOIA dataset?

### ISSUE THREAD

**Issue by zhaoxuyan** [YueLiao/PPDM#58]
including each verb's AP score?

**Comment by YueLiao** [comment]
Sorry for the latter response. I suddenly checked out from SenseTime due to Covid19, where I missed these checkpoints sorted in the SenseTime computer. You can implement it with the provided code. However, our experiments were conducted on the very initial HOI-A dataset, so implementation with the current HOI-A dataset may lead to a different performance from the paper reported.
